# -*- coding: utf-8 -*-
"""Supermarket_Sales_Analysis_and_Forcasting_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbc4GxJQ8ZwCHEj34x0tQZaT6pl3PCGG

Project : Supermarket sales analysis and forecasting

Author : S M Tanjimul Haque

One significant, high-impact use of artificial intelligence (AI) in business is supermarket sales research and forecasting, which turns unprocessed transaction data into useful, predictive insights. AI-driven, granular, and real-time forecasting greatly increases profitability, operational efficiency, and sustainability because grocery stores deal with high-volume, low-margin, and frequently perishable goods. This project can make a significant contribution in :
1. Drastic Improvements in Inventory Management
2. Intelligent Dynamic Pricing and Promotions
3. Operational Efficiency and Labour Optimization
4. Enhanced Customer Experience
5. Advanced Data Analytics for Strategic Growth

#Importing Essential Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

"""#Overview
**Overviewing the Data**

**Uploading the Dataset**
"""

from google.colab import files
uploaded = files.upload()

# dataset_path = '/content/drive/MyDrive/Colab Notebooks/supermarket_sales.csv'

"""#1. Introduction to the Dataset

**Reading the Dataset**
"""

# df = pd.read_csv(dataset_path)
# print(df)

df = pd.read_csv('supermarket_sales.csv')
print(df)

"""**Revealing the basic info about the train dataset and optimizing dtypes of variables to reduce memory usage.**"""

#Checking the Dimension of Data
print(df.shape)

#Checking the first 5 rows as to how data looks.
df.head()

# Describing Data

df.describe()

"""# Cleaning

# 2.Cleaning Data
"""

df.info()

# As non-null values are present in the dataset so we can proceed with this dataset

# checking and aggregating null values
df.isnull().sum()

"""## Removing Invoice Column as it is not usefull in our Analysis

---



---


"""

df=df.drop(['Invoice ID'],axis=1)

#checking that the Invoice Column is removed Successfully or not!
df.info()

# From the above dataset view we can see that the 'gross margin percentage' is same for everyone
df['gross margin percentage'].unique()

# This describe which row in the DataFrame is duplicated or not
df.duplicated().value_counts()

"""## As we do not have any null values and duplicate values we can now go ahead and convert the column values into their Corresponding data types


---
---




"""

df['Date']=pd.to_datetime(df['Date'])

df['Time']=pd.to_datetime(df['Time'])

# Reviewing our dataset
df.info()

# Now our data is clean and is ready to be used in the Analysis Phase

"""# Analyzing

# 3. Analysis

## Checking how many males and how many are female in our data
"""

df['Gender'].value_counts()

sns.catplot(x='Gender',kind='count',data= df)
sns.set(rc={'figure.figsize':(5,7)},palette='Paired')

"""##Analyzing the customer rating column"""

sns.displot(x='Rating',data=df,kde=True)
plt.show()

"""The distribution seems to be almost uniform with a slight deviation from the normal.Lets check the skewness of the distribution using skew function of pandas library"""

df['Rating'].skew()

#A skewnwss of 0.009 is very low and so the distribution can be said to be unskewed.

"""**Now i want to check the aggregate sales across the branches**"""

plt.pie(df['Branch'].value_counts(),labels=df['Branch'].unique(),autopct='%0.0f%%')
plt.show()

"""The pie chart represents the relative amount of total sales happening across branches A,B AND C.All three of these branches seem to be fairing well in thier respective locations.

**Lets see what is the most popular payment method used by customers**
"""

plt.pie(df['Payment'].value_counts(),labels=df['Payment'].unique(),autopct='%0.0f%%')
plt.show()

#E-wallet and Cash are the most used methods.

"""###Does gross income affect customer rating?"""

sns.lmplot(x='Rating',y='gross income',data=df,col='Customer type')

"""The linier model plot gives a scatter plot along with a linier model approximation of the data points .From the plot it seems like there is no relation between customers rating and the income the store generates on the order.

##Untill Now there are no interrelated insights, from which we can conclude or manupulate things upon.

##Lets Check ,which is the most profitable branch?
"""

sns.boxplot(x=df['Branch'],y=df['gross income'])

#Evidently the branch C is doing the better than the other branches by a small margin.

"""##Relationship between Gender and Gross Income"""

sns.boxplot(x='Gender',y='gross income',data=df)

#Gross income is similar for both male and female customers but there is a slightly higher mean of income generated from female.

"""##Trend in gross income"""

sns.lineplot(x=df.Date,y=df['gross income'])
plt.xticks(rotation=90)

"""As we can see in the plot above,there is no certain trend which the income generated follows depending on the time series of dates provided in the data set.

##Which product line generates the most income?
"""

df.head()

"""##Which product line helps generate the most income?"""

totalsales=df[["Product line","gross income"]].groupby(['Product line'],as_index= False).sum().sort_values(by= 'gross income',ascending= False)
totalsales

sns.barplot(x='Product line',y='gross income',data=totalsales)
sns.set(rc={'figure.figsize':(10,10)})
plt.xticks(rotation=45)

"""When we calculate the total sum of income generated from each product line ,we see that Food and Beverages AND Sports and Travel has the highest values.

##Spending pattern of both males and females(which category do they spend more)
"""

sns.countplot(data=df, x='Product line', hue='Gender', palette='Set2')
plt.xticks(rotation=45)

"""From the above graph we can notice that

*   Males spend more on Health and Beauty than females.
*   Females purchase more Fashion accessories and Sports and Travel than males.

##Which day of the week has maximum sales?
"""

df['day'] = df['Date'].dt.day_name()   #to get the day of the date column
df.head()

plt.figure(figsize=(10,8))
sns.barplot(x='day',y='gross income',data=df,estimator=sum)
#using estimator=sum parameter to get the total gross income for each day in our plot rather than the mean of gross income

"""Sales is highest on Saturday followed by Sunday and it was lowest on monday.Hence we can say that sales are higher on weekends and lower on weekdays.

##Now lets check which hour of the day is the busiest
"""

df['Hour']=df['Time'].dt.hour
df.head()

hourly_customer=df['Hour'].value_counts().reset_index()
hourly_customer

sns.lineplot(x='index',y='Hour',data=hourly_customer)
sns.set(rc={'figure.figsize':(14,7)})

"""Looks like the 19th hour,that is 7PM IN THE EVENING IS THE BUSIEST HOUR OF THE DAY WITH THE MOST AMOUNT OF CUSTOMERS PURCHASING ITEMS.

##What product line should the supermarket focus on?

HERE WE CAN HAVE TWO APPROCHES by which we can ANSWER THIS QUESTION.


1.   By looking for the highest rated product line.
2.   By looking for the most sold products.
"""

sns.barplot(x='Product line',y='Rating',data=df)
plt.figure(figsize=(12,10))

sns.barplot(x='Product line',y='Quantity',data=df,estimator=sum)

"""Rating for Fashion Accessories AND Food and Beverages is high but we can see that quantity purchased is high for Electronic accessories AND Food and Beverages.SO IN ORDER TO MEET THE DEMAND,Electronic accessories and Food and Beverages need to be on top priority.

##Now lets check where can we open a new store for expansion of the buisness
"""

sns.barplot(x='City',y='gross income',data=df,estimator=sum)

#Since the city NAYPYITAW has the highest mean gross income we should plan on expansion of branches in that city.

sns.countplot(data=df, x='Product line', hue='City')
plt.show()

rounded_corr_matrix = np.round(df.corr(), 2)
rounded_corr_matrix

plt.figure(dpi=125)
sns.heatmap(np.round(df.corr(),2),annot=True,cmap='RdYlBu_r')
plt.show()

df["Time"]= pd.to_datetime(df["Time"])
df["Hour"]= (df["Time"]).dt.hour
plt.figure(figsize=(14,6))
SalesTime = sns.lineplot(x="Hour", y ="Quantity", data = df)
plt.title("Product Sales per Hour")
plt.show()

plt.figure(dpi=125)
sns.countplot(y ='Product line', hue = "City", data = df)
plt.xlabel('Count')
plt.ylabel('Product Type')
plt.show()

"""## Analysis based upon gender"""

print(df.shape)
df['Gender'].value_counts()

sns.countplot(x='Gender',data=df)

gender_dummies=pd.get_dummies(df['Gender'])
gender_dummies.head()

df=pd.concat([df,gender_dummies],axis=1)
df.head()

plt.figure(figsize=(12,6))
sns.barplot(x="Product line",y="Female", data = df)

plt.figure(figsize=(12,6))
sns.barplot(x="Product line",y="Male", data = df)

"""# 4. Conclusions and Action to be taken

## Conclusions, scope of improvement & actions to be taken

* C brach has highest profit among all and females contribute to larger part of profit in all three branches.
* Food and Sports gives supermarket most sales whereas health gives less sales.
* males are more interested in healthcare products and least interested in fashion products
* females are spending more on fashion and least in sports.

## As, we concluded earlier supermarket sales are least in healthcare but males are most interested in healthcare products. so this means if volume of male customers increases, the healthcare section of supermarkets can see a rise.

* On mondays, sales are least & highest on saturday followed by tuesday.

## So, by means like sale events or any other attracting strategy organized on low sale-scoring days like mondays can improve sales and profits.

* 7 PM is the busiest hour of the day

## Arranging more staff around 19th hour colud help in fluency and hassle free shopping experience.

* Health section have highest ratings yet lowest sales.

## To improve this we have to attract more male customers.

* Yangon branch have highest sales in electronics and home supplies
* Mandalay branch have highest sales in sports and fashion
* Napatlay branch have highest sales in food and fashion

## Supermarket needs to focus on other categories that are not popular in any of three branches like healthcare and lifestyle section

* We can conclude that healthcare and lifestyle sector are'nt doing well.


---



---



---

# Forcasting

# 5. Prediction and Forcasting

**we make test cases using arima library and furthermore predicting the sales for upcoming one month.**

---
"""

from statsmodels.tsa.stattools import adfuller
dftest=adfuller(df['cogs'], autolag='AIC')
dfoutput=pd.Series(dftest[0:4], index=['Test Statistic','p-value','Lags Used','Number of Observations Used'])
for key,value in dftest[4].items():
    dfoutput['Critical Value (%s)'%key] = value
print(dfoutput)

!pip install pmdarima


from pmdarima.arima import auto_arima
stepwise_model = auto_arima(df["cogs"], start_p=1, start_q=1,
                            max_p=3, max_q=3, m=12,
                            start_P=0, seasonal=True,
                            d=1, D=1, trace=True,
                            error_action='ignore',
                            suppress_warnings=True,
                            stepwise=True)

print(stepwise_model.aic())

#importing Sarimax and passing the parameters
from statsmodels.tsa.statespace.sarimax import SARIMAX
m=SARIMAX(df['cogs'], order=(3,1,0),seasonal_order=(2,1,0,12))
res=m.fit()

df['arima_predict']=res.fittedvalues

forecast=res.predict(start=len(df),end=len(df)+35)
forecast

df['cogs'].append(forecast)

#plot between historical data and forecasted data
plt.figure(figsize=(20, 12))
plt.plot(df['cogs'],label="historical data")
plt.plot(forecast,label="forecasted data")
plt.legend()

"""##From this we can clearly see Supermarket's sales are going in uptrend according to prediction for upcoming next 30 days."""



"""##This model will help Supermarket to improve thier profits, eliminate thier mistakes."""



"""##with help of EDA and Predicting libraries we have analysed data in such a way that it asks important questions and helps us in making necessary decesions based upon the fact of analysed data."""

